### ISSUE TITLE
הציטוטים בפרויקט

### ISSUE THREAD

**Issue by shayaulman** [yitzhak-bloy/Random-Quote-Machine#7]
שלום :)
?אם מותר לשאול, מאיפה השגת את הציטוטים המיוחדים
דרך אגב, הפרויקט יפה מאוד!

**Comment by yitzhak-bloy** [comment]
שלום וברכה
...פשוט כתבתי בגוגל 'משפטי השראה' או משהו כזה ואספתי מכמה מקומות, לא זוכר אפילו מאיפה
